config/routes.rb
Rails.application.routes.draw do
  
  resources :time_slots
  resources :weekdays
  resources :polygons
  resources :places
  resources :fsas
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :postals
  resources :categories, except: [:destroy]
end

app/models/postal.rb
class Postal < ApplicationRecord
    
  scope :active_postals, -> {where(active: true)}
  scope :inactive_postals, -> {where(active: false)}
   
  validates :postalcode, presence: true, length: {minimum: 6, maximum: 6},  format: { with: /\A^(?!.*[DFIOQU])[A-VXY][0-9][A-Z] ?[0-9][A-Z][0-9]$\z/}

  
  validate :code_starts_with 
   
private
    def code_starts_with
        
      if !postalcode.start_with?(*Fsa.all.pluck(:fsacode))
        errors.add(:postalcode, "does not fall into Richmond")
      end
    end
     
   

end
 # belongs_to :fsa

app/controllers/postals_controller.rb
class PostalsController < ApplicationController

    before_action :set_postal, only: [:show, :edit, :update, :destroy]

def show
 
end

def index
    @postals = Postal.all

end

def edit
  
end

def new
  @postal = Postal.new
end

def create
@postal = Postal.new(postal_params)
if @postal.save
    
    flash[:notice] = "Postalcode was saved successfully"

redirect_to @postal


else
    
    render 'new'
end
end

def update 

if @postal.update(postal_params)
    
    flash[:notice] = "Postalcode was updated successfully"
    redirect_to @postal
else
  render 'edit'
end

end

def destroy
    
    @postal.destroy
    redirect_to postals_path
end

private

def set_postal
    @postal = Postal.find(params[:id])
end

def postal_params

    params.require(:postal).permit(:postalcode)
end

end

app/views/postals/_form.html.erb
<% if @postal.errors.any? %>
<h2> The following errors prevented the postalcode from being saved </h2>
<ul>
<% @postal.errors.full_messages.each do |msg| %>
<li><%= msg %></li> 
<% end %>

</ul>
<% end %>
<%= form_with(model: @postal, local: true) do |f| %>

<p>
<%= f.label :postalcode %>
<%= f.text_field :postalcode %>


</p>
<p>
<%= f.submit %>
</p>

<% end%>

app/views/postals/edit.html.erb
<h2>edit page</h2>

<%= render 'form'%>

<%= link_to "Cancel and Return to list of postal codes", postals_path%> |

app/views/postals/index.html.erb
<h2>Showing List of Postalcodes</h2>

<table>
 <thead>
   <tr>
   <th>Postalcode</th>
   <th colspan = "3">Actions</th>
   </tr>
   </thead>

   <tbody>
   <% @postals.each do |postal|%>
        <tr>
    <td><%= postal.postalcode%> </td>
    <td><%= link_to 'Show', postal_path(postal)%> </td>
    <td><%= link_to 'Edit', edit_postal_path(postal)%> </td>
    <td><%= link_to 'Delete', postal_path(postal), method: :delete, data: { confirm: "Are you sure?"}%></td>
</tr>
<% end %>
   </tbody>
   </table>

<p>
   <%= link_to 'Add new Postal code', new_postal_path%>
</p>

app/views/postals/new.html.erb
<h2>Enter new Postal Code</h2>


<%= render 'form'%>

<%= link_to "Return to list of postal codes", postals_path%> |

app/views/postals/show.html.erb
<h2>Showing Postal code with id: <strong><%=@postal.id%></strong></h2> 

<p><strong>Postalcode: </strong> <%= @postal.postalcode%><strong>  Submitted at: </strong><%= @postal.created_at%><</p>

<%= link_to "Edit", edit_postal_path(@postal)%> |
<%= link_to "Delete", postal_path(@postal), method: :delete, data: { confirm: "Are you sure?"} %> |
<%= link_to "Return to list of postal codes", postals_path%> |