config/routes.rb
Rails.application.routes.draw do
  
  resources :time_slots
  resources :weekdays
  resources :polygons
  resources :places
  resources :fsas
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :postals
  resources :categories, except: [:destroy]
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord

  has_many :weekday_time_slots
  has_many :weekday, through: :weekday_time_slots
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_slot_params
      params.require(:time_slot).permit(:time, :duration)
    end
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_with(model: time_slot, local: true) do |form| %>
  <% if time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <% time_slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing Time Slot</h1>

<%= render 'form', time_slot: @time_slot %>

<%= link_to 'Show', @time_slot %> |
<%= link_to 'Back', time_slots_path %>

app/views/time_slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Slots</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_slots.each do |time_slot| %>
      <tr>
        <td><%= time_slot.time %></td>
        <td><%= time_slot.duration %></td>
        <td><%= link_to 'Show', time_slot %></td>
        <td><%= link_to 'Edit', edit_time_slot_path(time_slot) %></td>
        <td><%= link_to 'Destroy', time_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Slot', new_time_slot_path %>

app/views/time_slots/new.html.erb
<h1>New Time Slot</h1>

<%= render 'form', time_slot: @time_slot %>

<%= link_to 'Back', time_slots_path %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @time_slot.time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @time_slot.duration %>
</p>

<%= link_to 'Edit', edit_time_slot_path(@time_slot) %> |
<%= link_to 'Back', time_slots_path %>