config/routes.rb
Rails.application.routes.draw do
  
  resources :time_slots
  resources :weekdays
  resources :polygons
  resources :places
  resources :fsas
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :postals
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fsa.rb
class Fsa < ApplicationRecord
   
   scope :active_fsas, -> { where(active: true) }
   scope :inactive_fsas, -> {where(active: false) }
   
    validates :fsacode, presence: true, length: {minimum: 3, maximum: 3},  format: { with: /\A^(?!.*[DFIOQU])[A-VXY][0-9][A-Z]$\z/}
   
    validates_uniqueness_of :fsacode
   
   
    has_many :postals



end

app/models/place.rb
class Place < ApplicationRecord
   
  geocoded_by :address
  
  before_validation :geocode, if: :address_changed?
  
  validates :name, presence: true 

  validates :address, presence: true
  
  validate :point_validation

  has_many :polygons

private
  
  def point_validation
    
    poly_array = Polygon.select("fsa_polygon @> point '(#{latitude}, #{longitude})' AS contained").map{ |p| p.contained }

    if !(valid_address = poly_array.include? true)
      errors.add(:address, "does not fall into delivery zone")
    end

  end

end

app/models/polygon.rb
class Polygon < ApplicationRecord
    
  validates :fsa, presence: true, uniqueness: true

  validates :fsa_polygon, presence: true

  belongs_to :weekday_time_slot
end

app/models/postal.rb
class Postal < ApplicationRecord
    
  scope :active_postals, -> {where(active: true)}
  scope :inactive_postals, -> {where(active: false)}
   
  validates :postalcode, presence: true, length: {minimum: 6, maximum: 6},  format: { with: /\A^(?!.*[DFIOQU])[A-VXY][0-9][A-Z] ?[0-9][A-Z][0-9]$\z/}

  
  validate :code_starts_with 
   
private
    def code_starts_with
        
      if !postalcode.start_with?(*Fsa.all.pluck(:fsacode))
        errors.add(:postalcode, "does not fall into Richmond")
      end
    end
     
   

end
 # belongs_to :fsa

app/models/time_slot.rb
class TimeSlot < ApplicationRecord

  has_many :weekday_time_slots
  has_many :weekday, through: :weekday_time_slots
end

app/models/weekday.rb
class Weekday < ApplicationRecord

    has_many :weekday_time_slots
    has_many :time_slots, through: :weekday_time_slots
end

app/models/weekday_time_slot.rb
class WeekdayTimeSlot < ApplicationRecord

  belongs_to :weekday
  belongs_to :time_slot
  has_many :polygons
end

app/models/zone.rb
class Zone < ApplicationRecord
  validates :sw_lon, :sw_lat, :ne_lon, :ne_lat, presence: true
end

app/controllers/fsas_controller.rb
class FsasController < ApplicationController
  before_action :set_fsa, only: [:show, :edit, :update, :destroy]

  # GET /fsas
  # GET /fsas.json
  def index
    @fsas = Fsa.all
  end

  # GET /fsas/1
  # GET /fsas/1.json
  def show
  end

  # GET /fsas/new
  def new
    @fsa = Fsa.new
  end

  # GET /fsas/1/edit
  def edit
  end

  # POST /fsas
  # POST /fsas.json
  def create
    @fsa = Fsa.new(fsa_params)

    respond_to do |format|
      if @fsa.save
        format.html { redirect_to @fsa, notice: 'Fsa was successfully created.' }
        format.json { render :show, status: :created, location: @fsa }
      else
        format.html { render :new }
        format.json { render json: @fsa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fsas/1
  # PATCH/PUT /fsas/1.json
  def update
    respond_to do |format|
      if @fsa.update(fsa_params)
        format.html { redirect_to @fsa, notice: 'Fsa was successfully updated.' }
        format.json { render :show, status: :ok, location: @fsa }
      else
        format.html { render :edit }
        format.json { render json: @fsa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fsas/1
  # DELETE /fsas/1.json
  def destroy
    @fsa.destroy
    respond_to do |format|
      format.html { redirect_to fsas_url, notice: 'Fsa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fsa
      @fsa = Fsa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fsa_params
      params.require(:fsa).permit(:fsacode)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about

    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  
  def get_locations
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{params[:latitude]},#{params[:longitude]}&radius=500&key=#{Rails.application.google}"
    http_call = open(url).read
    response = JSON.parse(http_call, {:symbolize_names => true})
    @locations = response{:results}
  end
  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :address, :latitude, :longitude)
    end
end

app/controllers/postals_controller.rb
class PostalsController < ApplicationController

    before_action :set_postal, only: [:show, :edit, :update, :destroy]

def show
 
end

def index
    @postals = Postal.all

end

def edit
  
end

def new
  @postal = Postal.new
end

def create
@postal = Postal.new(postal_params)
if @postal.save
    
    flash[:notice] = "Postalcode was saved successfully"

redirect_to @postal


else
    
    render 'new'
end
end

def update 

if @postal.update(postal_params)
    
    flash[:notice] = "Postalcode was updated successfully"
    redirect_to @postal
else
  render 'edit'
end

end

def destroy
    
    @postal.destroy
    redirect_to postals_path
end

private

def set_postal
    @postal = Postal.find(params[:id])
end

def postal_params

    params.require(:postal).permit(:postalcode)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fsas_helper.rb
module FsasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/polygons_helper.rb
module PolygonsHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/weekdays_helper.rb
module WeekdaysHelper
end

app/views/delivery_schedules/_form.html.erb
<%= form_with(model: delivery_schedule, local: true) do |form| %>
  <% if delivery_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery_schedule.errors.count, "error") %> prohibited this delivery_schedule from being saved:</h2>

      <ul>
      <% delivery_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fsa %>
    <%= form.text_field :fsa %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :delivery_day %>
    <%= form.text_field :delivery_day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg|%>

<%= msg %>
  <% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FSATest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
    <%= javascript_include_tag "https://unpkg.com/@turf/turf/turf.min.js" %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>about page</h2>

app/views/pages/home.html.erb
<h1>Point inside Polygon Home Page</h1>

  <%= link_to "Link to list of FSA Polygons Delivery Zones", polygons_path%><br><br>
  <%= link_to "Link to list of Addresses", places_path%><br><br>
  <%= link_to "Link to list of Delivery Days", weekdays_path%><br><br>
  <%= link_to "Link to list of Time slots", time_slots_path%><br><br>
 